# Generated by Django 5.2.7 on 2026-04-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='therapist_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
