# Generated by Django 5.2.7 on 2026-04-19 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_rdv_therapist_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReponseRendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_reponse', models.DateTimeField(auto_now_add=True)),
                ('lu_par_ergo', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.patientprofile')),
                ('rendez_vous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_patient', to='Dashboard.rdv')),
            ],
        ),
    ]
