# Generated by Django 5.2.7 on 2026-04-21 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_delete_patient_patientprofile_statut_programme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnexionPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_connexion', models.DateTimeField(auto_now_add=True)),
                ('page_visitee', models.CharField(blank=True, max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connexions', to='Dashboard.patientprofile')),
            ],
            options={
                'ordering': ['-date_connexion'],
            },
        ),
    ]
