# Generated by Django 5.2.7 on 2026-04-21 12:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_connexionpatient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defipatient',
            options={},
        ),
        migrations.AddField(
            model_name='defipatient',
            name='date_completion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defipatient',
            name='points_gagnes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='defipatient',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.patientprofile'),
        ),
        migrations.CreateModel(
            name='Defi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('points', models.IntegerField(default=10)),
                ('niveau_requis', models.CharField(choices=[('bronze', '🥉 Bronze'), ('argent', '🥈 Argent'), ('or', '🥇 Or'), ('platine', '💎 Platine')], default='bronze', max_length=20)),
                ('repetition_requise', models.IntegerField(default=1)),
                ('amplitude_minimale', models.IntegerField(default=0)),
                ('douleur_maximale', models.IntegerField(default=10)),
                ('ordre', models.IntegerField(default=0)),
                ('exercice_requis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dashboard.exercice')),
            ],
            options={
                'ordering': ['ordre', 'points'],
            },
        ),
        migrations.AddField(
            model_name='defipatient',
            name='defi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.defi'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='defipatient',
            unique_together={('patient', 'defi')},
        ),
        migrations.CreateModel(
            name='ProgressionGlobale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_actuel', models.CharField(choices=[('bronze', '🥉 Bronze'), ('argent', '🥈 Argent'), ('or', '🥇 Or'), ('platine', '💎 Platine')], default='bronze', max_length=20)),
                ('points_totaux', models.IntegerField(default=0)),
                ('defis_completes', models.IntegerField(default=0)),
                ('derniere_progression', models.DateField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.patientprofile')),
            ],
        ),
        migrations.RemoveField(
            model_name='defipatient',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='defipatient',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='defipatient',
            name='description',
        ),
        migrations.RemoveField(
            model_name='defipatient',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='defipatient',
            name='objectif',
        ),
        migrations.RemoveField(
            model_name='defipatient',
            name='progression',
        ),
        migrations.RemoveField(
            model_name='defipatient',
            name='termine',
        ),
    ]
