# Generated by Django 5.2.7 on 2026-04-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_alter_defipatient_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defi',
            options={'ordering': ['ordre']},
        ),
        migrations.RemoveField(
            model_name='defi',
            name='amplitude_minimale',
        ),
        migrations.RemoveField(
            model_name='defi',
            name='douleur_maximale',
        ),
        migrations.RemoveField(
            model_name='defi',
            name='exercice_requis',
        ),
        migrations.RemoveField(
            model_name='defi',
            name='repetition_requise',
        ),
    ]
