# Generated by Django 5.2.7 on 2026-04-21 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_alter_defi_options_remove_defi_amplitude_minimale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeEnvoye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.JSONField(default=dict)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('est_lu', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes_recus', to='Dashboard.patientprofile')),
            ],
        ),
    ]
