# Generated by Django 5.2.7 on 2026-04-21 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_programmeenvoye'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmeenvoye',
            options={'ordering': ['-date_envoi']},
        ),
    ]
