# Generated by Django 5.2.7 on 2026-04-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_alter_programmeenvoye_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliothequeexercice',
            name='repos',
            field=models.CharField(blank=True, default='45s', max_length=100, verbose_name='Temps de repos'),
        ),
        migrations.AddField(
            model_name='exercice',
            name='repos',
            field=models.CharField(blank=True, default='45s', max_length=100, verbose_name='Temps de repos'),
        ),
        migrations.AlterField(
            model_name='bibliothequeexercice',
            name='temps_exercice',
            field=models.CharField(blank=True, max_length=100, verbose_name="Durée de l'exercice"),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='temps_exercice',
            field=models.CharField(blank=True, max_length=255, verbose_name="Durée de l'exercice"),
        ),
    ]
