# Generated by Django 5.2.7 on 2026-04-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0011_bibliothequeexercice_repos_exercice_repos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmeenvoye',
            options={},
        ),
        migrations.AddField(
            model_name='programmeenvoye',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
