# Generated by Django 5.2.7 on 2026-04-23 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0012_alter_programmeenvoye_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationErgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('resultat_exercice', 'Résultat exercice'), ('message_patient', 'Message patient'), ('rdv', 'Rendez-vous')], max_length=50)),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField(blank=True)),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('ergo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_ergo', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_envoyees', to='Dashboard.patientprofile')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
