# Generated by Django 5.2.7 on 2026-04-23 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0013_notificationergo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationErgo',
        ),
    ]
