# Generated by Django 5.2.7 on 2026-04-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0015_resultatexercice_statut_ergo'),
    ]

    operations = [
        migrations.AddField(
            model_name='defipatient',
            name='statut',
            field=models.CharField(choices=[('assigned', 'Assigné'), ('completed', 'Terminé')], default='assigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='defipatient',
            name='points_gagnes',
            field=models.IntegerField(default=0),
        ),
    ]
