# Generated by Django 5.2.7 on 2026-04-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0016_add_defipatient_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiqueaction',
            name='type_action',
            field=models.CharField(choices=[('seance', 'Séance'), ('message', 'Message'), ('ressource', 'Ressource'), ('dossier', 'Dossier'), ('programme', 'Programme'), ('ia', 'IA'), ('patient', 'Patient'), ('visite', 'Visite')], max_length=20, verbose_name="Type d'action"),
        ),
    ]
