# Generated by Codex on 2026-05-02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0017_alter_historiqueaction_type_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question du jour')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_jour_creees', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_jour', to='Dashboard.patientprofile', verbose_name='Patient destinataire')),
            ],
            options={
                'verbose_name': 'Question du jour',
                'verbose_name_plural': 'Questions du jour',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ReponseQuestionJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.CharField(max_length=20)),
                ('douleur', models.IntegerField(default=0)),
                ('fatigue', models.IntegerField(default=0)),
                ('humeur', models.CharField(blank=True, max_length=20)),
                ('satisfaction', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('date_reponse', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_questions_jour', to='Dashboard.patientprofile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='Dashboard.questionjour')),
            ],
            options={
                'verbose_name': 'Réponse à la question du jour',
                'verbose_name_plural': 'Réponses aux questions du jour',
                'ordering': ['-date_reponse'],
            },
        ),
    ]
